---
title: "SCE Demo"
output: html_document
date: "2023-02-16"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
cancDiscSeurat <- 
  "~/1A_Jordan_Lab/Projects/scExploreR_files/scExploreR/Seurat_Objects/Cancer_discovery_object/pei_cd_20221122.Rds"

# Directory for SingleCellExperiment HDF5 version 
hdf5Dir <-
  "~/1A_Jordan_Lab/Projects/scExploreR_files/scExploreR/Seurat_Objects/Cancer_discovery_object/sce_hdf5"
```


# Seuart to SingleCellExperiment Object

```{r}
# Load a Seurat object
sobj <- readRDS(cancDiscSeurat)

sobj

# Convert to SingleCellExperiment object 
# Each assay must be converted separately
sce <- as.SingleCellExperiment(sobj, assay = "RNA")
sceAdt <- as.SingleCellExperiment(sobj, assay = "ADT")

# Store ADT assay as an "alternate experiment" of the RNA assay
altExps(sce) <- list("ADT" = sce_adt)

sce
```

# Save in HDF5 Format

```{r}
HDF5Array::saveHDF5SummarizedExperiment(sce, dir = hdf5Dir, chunkdim = c(1000, 1000))
```

# Load HDF5 File

```{r}
sce <- HDF5Array::loadHDF5SummarizedExperiment(dir = hdf5Dir)

print(object.size(sce), units = "auto")
```

# Object Exploration
## Assay Equivalent: "Experiments"
```{r}
# Main experiment (RNA by convention) selected by default
sce

# To view ADT information
altExpNames(sce)

altExps(sce)[["ADT"]]
```

## "Slot" Equivalent: Assays

```{r}
# View assay names
assayNames(sce)

assays(sce)[["logcounts"]]
```

## Reductions: accessed via reducedDims()

```{r}
reducedDimNames(sce)

reducedDims(sce)[["UMAP"]]
```

## Metadata: stored in colData
Metadata can also be accessed via the `$` operator, or via `[[`.

```{r}
colData(sce)

sce$named_clusters

sce[["named_clusters"]]
```

# Subsetting

```{r}
subset <- sce[, (sce$named_clusters %in% c("HSC", "Monocytes") & 
          sce$sample %in% c("Dx"))]

subset

# Inspect "tree" of delayed operations on delayedMatrix elements
countsMat <- assay(subset, "counts")
showtree(countsMat)
```

# Using Seurat Plots with SCE objects

```{r}
library(SCEPlots)

SCEPlots::DimPlot(
  object = sce,
  reduction = "UMAP",
  group_by = "named_clusters",
  #split_by = "sample",
  label = TRUE
)
```

