---
title: "Test_object_generation"
output: html_document
date: "2023-02-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Generation of test object

```{r}
library(Seurat)
library(SingleCellExperiment)
library(DelayedArray)
library(HDF5Array)
library(DelayedMatrixStats)

library(ggplot2)
library(dplyr)

# object to use: triana et al test dataset
sobj <- 
  readRDS(
    "../Triana_et_al_Reference/hosted_example_Triana_et_al_2021_young_partial_transcriptome_197Ab_collapsed.rds"
    )
```
 
```{r}
set.seed(325)

# Subset while downsampling on condensed_cell_type
AML_Seurat <- 
  subset(
    SetIdent(sobj, value = "condensed_cell_type"),
    downsample = 25
    ) 

# Add dataset to data/ folder
usethis::use_data(AML_Seurat)
```
 
```{r}
# Convert object to SCE format
sce <- as.SingleCellExperiment(AML_Seurat, assay = "RNA")
sce_ab <- as.SingleCellExperiment(AML_Seurat, assay = "AB")

altExps(sce) <- list("AB" = sce_ab)

sce

# Save in HDF5 format
saveHDF5SummarizedExperiment(
  sce, 
  dir = "inst/extdata/AML_sce"
  )

AML_sce <- loadHDF5SummarizedExperiment(
  dir = "inst/extdata/AML_sce"
)
```

