# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:  #[workflow_dispatch]
  pull_request:
    branches: [workflow_dispatch]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) py=${{ matrix.config.python }}

    strategy:
      fail-fast: false
      matrix:
        config:
          #- { os: macOS-latest  , r: 'release', python: '3.9' }
          #- { os: windows-latest, r: 'release', python: '3.9' }
          #- { os: ubuntu-latest , r: 'release', python: '3.9' }

          #- { os: ubuntu-latest, r: 'oldrel-1', python: '3.9' }
          #- { os: ubuntu-latest, r: 'oldrel-2', python: '3.9' }
          #- { os: ubuntu-20.04,  r: '3.6',      python: '3.8' }
          # - { os: ubuntu-latest, r: 'devel'   , python: '3.8', http-user-agent: 'release' }

          #- { os: ubuntu-latest, r: 'release', python: '3.7'  }
          #- { os: ubuntu-latest, r: 'release', python: '3.8'  }
          #- { os: ubuntu-latest, r: 'release', python: '3.10' }
          #- { os: ubuntu-latest, r: 'release', python: '3.11' }
          - { os: ubuntu-latest, r: 'release', python: '3.12' }
          - { os: macOS-latest, r: 'release', python: '3.12' }
          - { os: windows-latest, r: 'release', python: '3.12' }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          
      - uses: actions/setup-python@v4
        if: matrix.config.python != 'debug'
        with:
          python-version: ${{ matrix.config.python }}

      - name: setup r-reticulate venv
        shell: Rscript {0}
        run: |

          library(reticulate)

          path_to_venv <- virtualenv_create(
            envname = "r-reticulate",
            python = Sys.which("python"), # placed on PATH by the setup-python action
            packages = c(
              "docutils", "pandas", "scipy", "matplotlib", "ipython",
              "tabulate", "plotly", "psutil", "kaleido", "wrapt",
              "anndata"
            )
          )

          writeLines(
            paste0("RETICULATE_PYTHON=", virtualenv_python(path_to_venv)),
            Sys.getenv("GITHUB_ENV"))
            
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          error-on: '"error"'
